[[language]]
name = "dart"
auto-format = true

[[language]]
name = "rust"
auto-format = true
# config.check.command = "clippy"

# If this doesn't work, you might be on a older release version which handles this differently.
# Try using [language.config.check] instead of [language-server.rust-analyzer.config.check]
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
# language-servers = [ "pyright"]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[[language]]
name = "json"
auto-format = true

[[language]]
name = "toml"
auto-format = true
