#!/bin/sh
set -e

cleanup() {
    exec 3>&-
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    lf "$@"
else
    [ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
    trap cleanup EXIT
    lf "$@" 3>&-
fi
