#!/usr/bin/env bash

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Auto Start
riverctl spawn "mako"
killall "wlsunset"
riverctl spawn "wlsunset -t 3400 -T 3401"
riverctl spawn "eww daemon"
riverctl spawn "eww open bar"
killall "swaybg"
riverctl spawn "swaybg -i ~/wallpaper.png -m stretch"

riverctl map normal Super+Shift Return spawn kitty
riverctl map normal Super R spawn "rofi -show drun"
riverctl map normal Super B spawn zen-browser
riverctl map normal Super T spawn "kitty -e fish -c yazi" 

# Reload river configuration
riverctl map normal Super+Shift R spawn "~/.config/river/init"

# Close all eww windows
riverctl map normal Super Y spawn "eww close-all"

# Super+Q to close the focused view
riverctl map normal Super+Shift C close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd filtile "main-ratio -10"
riverctl map normal Super L send-layout-cmd filtile "main-ratio +10"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd filtile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd filtile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal Super P toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift P set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{W,D,S,A} to change layout orientation
riverctl map normal Super W send-layout-cmd filtile "main-location top"
riverctl map normal Super D send-layout-cmd filtile "main-location right"
riverctl map normal Super S send-layout-cmd filtile "main-location bottom"
riverctl map normal Super A send-layout-cmd filtile "main-location left"

# Cycle through tags
# riverctl map normal Super bracketleft spawn "cycle-focused-tags previous 6"
# riverctl map normal Super bracketright spawn "cycle-focused-tags next 6"

# Print
riverctl map normal None Print spawn "fish -c 'grim -g (slurp) ~/Images/Screenshot/(date).png'"
riverctl map normal Super Print spawn "fish -c 'grim -g (slurp) - | wl-copy'"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pipewire audio volume with wirepumbler
    riverctl map $mode None XF86AudioRaiseVolume spawn 'wpctl set-volume -l 1 @DEFAULT_SINK@ 2%+'
    riverctl map $mode Super Equal               spawn 'wpctl set-volume -l 1 @DEFAULT_SINK@ 2%+'
    riverctl map $mode None XF86AudioLowerVolume spawn 'wpctl set-volume -l 1 @DEFAULT_SINK@ 2%-'
    riverctl map $mode Super Minus               spawn 'wpctl set-volume -l 1 @DEFAULT_SINK@ 2%-'
    riverctl map $mode None XF86AudioMute        spawn 'wpctl set-mute @DEFAULT_SINK@ toggle'
    riverctl map $mode Super Slash               spawn 'wpctl set-mute @DEFAULT_SINK@ toggle'
done

# Set background and border color
riverctl background-color 0x002B36
riverctl border-color-focused 0xFF9A00
riverctl border-color-unfocused 0xA1A1A1
riverctl border-width 2

riverctl xcursor-theme "Nordzy-cursors" 48

# Set keyboard repeat rate
riverctl set-repeat 60 300

# Set keyboard layout
riverctl keyboard-layout br

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add float -app-id 'float*' -title 'foo'

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add csd -app-id "bar"

# Make all borders visible
riverctl rule-add ssd

# Mouse focus follow
riverctl focus-follows-cursor normal

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout filtile
filtile \
view-padding 0, \
outer-padding 0 &
