#! /bin/fish

# Change rustup to default
rustup default stable

# Install paru
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm paru -rf

# Use doas instead of sudo
doas nvim /etc/paru.conf

# Install AUR packages    
paru -S awesome-git nvim-packer-git librewolf-bin ttf-ms-fonts tradingview\
 jmtpfs epson-inkjet-printer-escpr mangal-bin

# Remove orphans
paru -Rsn (paru -Qtdq)

# Make startx works with awesome
cp /etc/X11/xinit/xinitrc ~/.xinitrc
nvim ~/.xinitrc

# Default zathura with pdf reader, not GIMP
xdg-mime default org.pwmt.zathura.desktop application/pdf

# Set X11 keyboard
doas localectl set-x11-keymap br
