#! /bin/fish

# Change rustup to default
rustup default stable

# Install paru
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
cd ..
rm paru-bin -rf

# Use doas instead of sudo
doas nvim /etc/paru.conf

# Install AUR packages    
paru -S awesome-git librewolf-bin ttf-ms-fonts tradingview fastfetch jmtpfs\
	epson-inkjet-printer-escpr mangal-bin xpadneo-dkms-git cava mangohud\
	ani-cli-git

# Set X11 keyboard
doas localectl set-x11-keymap br
